import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import SessionProviderWrapper from '@/app/components/SessionProviderWrapper';
import { TurnoProvider } from '@/app/context/TurnoContext'; // Importamos TurnoProvider

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SessionProviderWrapper>
          <TurnoProvider> {/* Envolvemos todo lo que necesite turno */}
            {children}
          </TurnoProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
